// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzsmjkhekmihlbckxabf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6c21qa2hla21paGxiY2t4YWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjMwMDQsImV4cCI6MjA2NDU5OTAwNH0.C2A9xPEhX4_XVSp2r5_IqD1AU8ykTVFhN2XAW3C40JY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);